import os
from datetime import timedelta, timezone
SINI = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BERKAS = os.path.join(SINI, 'data-arka.json')
BERKAS_SOAL = os.path.join(SINI, 'soal-arka.json')
BERKAS_LAGU = os.path.join(SINI, 'soal-lagu.json')
WIB = timezone(timedelta(hours=7))
CHANNEL_ARENA = 1535810881634570372
CHANNEL_REKAP = 1535836590264557599
CHANNEL_STATISTIK = 1535960574263820338
CHANNEL_QUEST = 1535918526156767242
CHANNEL_CUACA = CHANNEL_QUEST
CHANNEL_PERINTAH = {'trivia': 1535917622036791367, 'lagu': 1535919887673856073, 'tambahlagu': 1535919887673856073, 'akinator': 1535917843965550692, 'turnamen': 1535967723836940379, 'balon': 1535920221884518452, 'lomba': 1535920856658874460, 'lombatutup': 1535920856658874460, 'acara': [1535919366426730506, 1535921034891628645], 'acaralist': [1535919366426730506, 1535921034891628645], 'acarahapus': [1535919366426730506, 1535921034891628645], 'acaraedit': [1535919366426730506, 1535921034891628645], 'backup': 'semua', 'misi': CHANNEL_QUEST, 'gantimisi': CHANNEL_QUEST, 'toko': 1535916450533998632, 'beli': 1535916450533998632, 'tas': 1535916450533998632, 'panduan': 'semua', 'hunt': 1535916648765063300, 'koleksi': 1535916648765063300, 'duel': 1535968024937500722, 'tebak': 1535967600520073306, 'suit': 1535967723836940379, 'level': CHANNEL_STATISTIK, 'absen': CHANNEL_QUEST, 'cuaca': CHANNEL_QUEST, 'papan': CHANNEL_REKAP, 'statistik': CHANNEL_REKAP, 'rekap': CHANNEL_REKAP, 'profil': CHANNEL_STATISTIK, 'absenbulan': CHANNEL_STATISTIK, 'kasih': 'semua', 'pet': 'semua', 'kasihmakan': 'semua', 'kapsul': 'semua', 'rantai': 'semua', 'riwayat': 1535916450533998632, 'wishlist': 1535916450533998632, 'kasihitem': 1535916450533998632, 'pakai': 1535916450533998632, 'bantuan': 0, 'tambahsoal': 0, 'daftarsoal': 0, 'aturxp': 'semua'}
JAM_CUACA = 7
KATEGORI_GAME = {'Quiz & Trivia': ['trivia'], 'Summer Events': ['balon'], 'Games': ['hunt'], 'Summer Contest': ['lomba'], 'Summer Games': ['tebak', 'suit', 'duel', 'turnamen'], 'Kata & Rantai': ['rantai'], 'Tebak Tebakan': ['lagu', 'akinator']}
NAMA_GAME = {'trivia': 'Trivia', 'balon': 'Perang Balon', 'hunt': 'Jelajah Pantai', 'tebak': 'Tebak Angka', 'suit': 'Suit', 'duel': 'Duel', 'lomba': 'Lomba Kiriman', 'rantai': 'Rantai Kata', 'lagu': 'Tebak Lagu', 'akinator': 'Akinator', 'turnamen': 'Turnamen Suit'}
HARI_REKAP = 0
JAM_REKAP = 8
XP_CHAT = (8, 15)
JEDA_CHAT = 60
MINIMAL_HURUF = 4
XP_VOICE = 12
JEDA_VOICE = 300
TINGKAT = [(0, 'Shoreline', None), (300, 'Shallows', 'Shallows'), (900, 'Reef', 'Reef'), (2000, 'Open Sea', 'Open Sea'), (4000, 'Deep Current', 'Deep Current'), (7500, 'The Trench', 'The Trench')]
ROLE_JUARA = 'Wave Champion'
CUACA = [('Air Tenang', 1.0, '🌤️', 'Hari biasa. Santai aja.'), ('Air Tenang', 1.0, '🌤️', 'Ga ada yang istimewa hari ini.'), ('Angin Segar', 1.5, '🌬️', 'Anginnya enak, XP naik satu setengah kali.'), ('Ombak Besar', 2.0, '🌊', 'OMBAK BESAR! XP dobel seharian!'), ('Kabut', 0.8, '🌫️', 'Kabut tebal, semuanya jadi lambat.'), ('Badai', 3.0, '⛈️', 'BADAI! XP tiga kali lipat, tapi cuma hari ini!')]
TEBAK_MAKS = 100
TEBAK_KESEMPATAN = 7
DUEL_TARUHAN = 50
DUEL_MIN = 10
DUEL_MAKS = 5000
DUEL_DM = True
BALON_HADIAH = 90
BALON_TUNGGU = (3, 9)
TRIVIA_WAKTU = 35
TRIVIA_PETUNJUK = 18
TRIVIA_HADIAH = 80
TRIVIA_CEPAT = 40
TRIVIA_JEDA_ORANG = 30
WAKTU_KATEGORI = {'hots': (90, 45, 130, 70)}
HUNT_JEDA = 300
TANGKAPAN = [('sandal jepit sebelah', '🩴', 18, 5), ('botol plastik', '🧴', 15, 5), ('kerang kecil', '🐚', 15, 20), ('ikan teri', '🐟', 14, 25), ('kepiting', '🦀', 12, 40), ('bintang laut', '⭐', 9, 55), ('ubur ubur', '🪼', 7, 60), ('gurita', '🐙', 5, 90), ('penyu', '🐢', 3, 150), ('botol berisi pesan', '📜', 1.5, 220), ('peti harta karun', '🧰', 0.5, 400)]
KATEGORI_SOAL = {}
BACKUP_BERKAS = ['data-arka.json', 'soal-arka.json', 'soal-lagu.json', 'revive.json', 'pengumuman.json', 'reaction-role.json', 'warn.json', 'resources.json', 'tiket.json', 'setelan-dirga.json', 'tempban.json', 'starboard.json', 'profil-user.json', 'undangan.json']
CHANNEL_CADANGAN = 1536369402419744789
JAM_BACKUP = 3
MISI_PILIHAN = [('chat', 'Ngobrol {n} pesan di server', 12, 60), ('hunt', 'Jelajah pantai {n} kali', 3, 70), ('trivia', 'Jawab bener {n} soal trivia', 1, 90), ('suit', 'Menangin {n} pertandingan suit', 2, 80), ('balon', 'Nyamber {n} balon duluan', 1, 90), ('tebak', 'Tebak angka gua sampai kena {n} kali', 1, 90), ('duel', 'Menangin {n} duel', 1, 100), ('absen', 'Absen hari ini', 1, 40)]
MISI_JUMLAH = 3
MISI_BONUS = 200
MISI_MINGGU_HARI = 4
MISI_MINGGU_XP = 800
MISI_DM = True
CHANNEL_MISI = CHANNEL_QUEST
JAM_MISI = 7
BARANG = [('kerang', '🐚', 'Kerang Ajaib', 300, 'Ganti satu misi harian yang lo ga suka. Pakai `/gantimisi`.'), ('kail', '🎣', 'Kail Perak', 450, 'Dua jelajah berikutnya, peluang dapet barang langka naik tiga kali.'), ('umpan', '🪝', 'Umpan Emas', 500, 'Tiga kali jelajah pantai berikutnya XP-nya dobel.'), ('cepat', '⏩', 'Air Pasang', 600, 'Satu jam ke depan, jeda jelajah cuma 1 menit.'), ('lumba', '🐬', 'Sahabat Lumba lumba', 700, 'Misi harian yang ga kelar tetep dibayar setengah. Kepakai otomatis.'), ('perisai', '🛡️', 'Perisai Beruntun', 800, 'Sekali kalah suit ga mutusin runtutan lo. Kepakai otomatis.'), ('tiket', '⛵', 'Tiket Kapal', 1000, 'Bolong absen sehari ga mutusin runtutan. Kepakai otomatis.'), ('paus', '🐋', 'Paus Raksasa', 1500, 'Sehari penuh, semua XP yang lo dapet naik 50 persen.'), ('julukan', '🏷️', 'Julukan Sendiri', 1200, 'Bikin role warna sendiri lengkap sama namanya, tahan seminggu. Pakai `/pakai julukan`.'), ('namapet', '🐣', 'Hak Nama Nemo', 1800, 'Ganti nama peliharaan server sesuka lo. Semua orang bakal liat. Pakai `/pakai namapet`.')]
JULUKAN_HARI = 7
KAIL_PENGALI = 3
PAUS_TAMBAHAN = 0.5
TOKO_KELOMPOK = {'murah': (['kerang', 'kail', 'umpan', 'cepat'], 2), 'mahal': (['lumba', 'perisai', 'tiket'], 2), 'sosial': (['julukan', 'namapet'], 1)}
TOKO_SUPER = ['paus']
TOKO_SUPER_PELUANG = 0.25
BATAS_BELI = {'paus': 2}
CHANNEL_TOKO = 1535916450533998632
JAM_TOKO = 7
CEPAT_JEDA = 60
CEPAT_LAMA = 60
LAGU_JEDA_TAHAP = 20
LAGU_HADIAH = [150, 100, 60, 30]
LAGU_JEDA_ORANG = 30
AKI_MAKS_TANYA = 12
AKI_HADIAH_MENANG = 120
AKI_WAKTU = 120
AKI_SIFAT = {'hidup': 'Yang lo pikirin itu makhluk hidup?', 'hewan': 'Itu hewan?', 'air': 'Dia hidup atau dipakai di air?', 'terbang': 'Dia bisa terbang?', 'besar': 'Ukurannya lebih besar dari manusia dewasa?', 'kaki': 'Dia punya kaki?', 'peliharaan': 'Orang biasa melihara dia di rumah?', 'dimakan': 'Orang Indonesia biasa makan dia?', 'indonesia': 'Dia gampang ditemuin di Indonesia?', 'pantai': 'Dia sering ada di pantai?', 'buatan': 'Itu barang buatan manusia?', 'listrik': 'Butuh listrik atau baterai?', 'dibawa': 'Muat dibawa pakai satu tangan?', 'rumah': 'Biasanya ada di dalam rumah?', 'harian': 'Lo pakai dia hampir tiap hari?', 'keras': 'Bahannya keras?', 'suara': 'Dia bisa ngeluarin suara sendiri?', 'beroda': 'Dia punya roda?', 'penjaga': 'Dia biasa dipakai jagain rumah?', 'gambar': 'Dia nampilin gambar bergerak?', 'saku': 'Muat dimasukin kantong celana?', 'wadah': 'Dia bisa dipakai nampung air?'}
AKI_SUBJEK = {'kucing': ['hidup', 'hewan', 'kaki', 'peliharaan', 'indonesia', 'suara'], 'anjing': ['hidup', 'hewan', 'kaki', 'peliharaan', 'indonesia', 'suara', 'penjaga'], 'ayam': ['hidup', 'hewan', 'kaki', 'dimakan', 'indonesia', 'suara', 'peliharaan'], 'sapi': ['hidup', 'hewan', 'kaki', 'besar', 'dimakan', 'indonesia', 'suara'], 'gajah': ['hidup', 'hewan', 'kaki', 'besar', 'suara'], 'burung': ['hidup', 'hewan', 'kaki', 'terbang', 'peliharaan', 'indonesia', 'suara'], 'nyamuk': ['hidup', 'hewan', 'kaki', 'terbang', 'indonesia', 'suara'], 'ikan': ['hidup', 'hewan', 'air', 'dimakan', 'indonesia', 'pantai'], 'hiu': ['hidup', 'hewan', 'air', 'besar', 'pantai'], 'kepiting': ['hidup', 'hewan', 'air', 'kaki', 'dimakan', 'indonesia', 'pantai'], 'penyu': ['hidup', 'hewan', 'air', 'kaki', 'pantai', 'indonesia'], 'gurita': ['hidup', 'hewan', 'air', 'pantai', 'dimakan'], 'kelapa': ['hidup', 'besar', 'indonesia', 'pantai', 'dimakan'], 'rumput laut': ['hidup', 'air', 'dimakan', 'indonesia', 'pantai'], 'handphone': ['buatan', 'listrik', 'dibawa', 'rumah', 'harian', 'keras', 'suara', 'gambar', 'saku'], 'laptop': ['buatan', 'listrik', 'dibawa', 'rumah', 'harian', 'keras', 'suara', 'gambar'], 'kulkas': ['buatan', 'listrik', 'besar', 'rumah', 'harian', 'keras'], 'kipas angin': ['buatan', 'listrik', 'rumah', 'harian', 'keras', 'suara'], 'televisi': ['buatan', 'listrik', 'rumah', 'harian', 'keras', 'suara', 'gambar'], 'mobil': ['buatan', 'besar', 'keras', 'beroda', 'suara', 'indonesia'], 'sepeda': ['buatan', 'keras', 'beroda', 'indonesia'], 'motor': ['buatan', 'keras', 'beroda', 'suara', 'indonesia', 'harian'], 'kapal': ['buatan', 'air', 'besar', 'keras', 'suara', 'pantai'], 'sendok': ['buatan', 'dibawa', 'rumah', 'harian', 'keras', 'saku'], 'gelas': ['buatan', 'dibawa', 'rumah', 'harian', 'keras', 'wadah'], 'bantal': ['buatan', 'dibawa', 'rumah', 'harian'], 'handuk': ['buatan', 'dibawa', 'rumah', 'harian', 'pantai'], 'payung': ['buatan', 'dibawa', 'rumah', 'keras', 'pantai'], 'sandal': ['buatan', 'dibawa', 'rumah', 'harian', 'pantai', 'indonesia'], 'kacamata': ['buatan', 'dibawa', 'harian', 'keras', 'pantai', 'saku'], 'gitar': ['buatan', 'dibawa', 'rumah', 'keras', 'suara', 'indonesia'], 'jam dinding': ['buatan', 'listrik', 'rumah', 'keras', 'suara']}
TURNAMEN_MIN = 2
TURNAMEN_MAKS = 16
TURNAMEN_DAFTAR_MENIT = 5
TURNAMEN_PILIH_DETIK = 45
TURNAMEN_HADIAH = [500, 250, 100]
ARSIP_HARI = 30
SEASON_AKTIF = True
SEASON_BULAN = 3
SEASON_JUARA_DISIMPAN = 5
SEASON_SISA_PERSEN = 0.25
QUEST_AKTIF = True
QUEST_HARI = 0
QUEST_BONUS = 350
QUEST_PILIHAN = [('chat', 'Kirim {n} pesan rame rame', 600), ('hunt', 'Jelajah pantai {n} kali sekampung', 120), ('trivia', 'Jawab bener {n} soal trivia', 40), ('lagu', 'Tebak bener {n} lagu', 25), ('rantai', 'Sambung {n} kata di rantai kata', 150), ('absen', 'Kumpulin {n} absen dalam seminggu', 80)]
LENCANA = [('ngobrol', '💬', 'Tukang Ngobrol', 'Kirim 500 pesan', 'pesan', 500), ('suara', '🎙️', 'Betah di Voice', 'Nongkrong 600 menit', 'menit', 600), ('rajin', '📅', 'Ga Pernah Bolos', 'Absen 14 hari beruntun', 'absen_panjang', 14), ('jawara', '⚔️', 'Jawara', 'Menang 50 kali', 'menang', 50), ('juara', '🏆', 'Penguasa Ombak', 'Juara mingguan 3 kali', 'juara', 3)]
LENCANA_KHUSUS = [('kolektor', '🐚', 'Kolektor Pantai', 'Nemu semua jenis tangkapan'), ('dermawan', '🤝', 'Dermawan', 'Kasih XP ke 5 orang berbeda')]
KASIH_AKTIF = True
KASIH_MIN = 10
KASIH_MAKS_HARIAN = 500
KASIH_POTONGAN = 0.1
KASIH_ITEM_AKTIF = True
KASIH_ITEM_HARIAN = 3
KASIH_ITEM_DILARANG = ['julukan', 'namapet']
WISHLIST_AKTIF = True
WISHLIST_MAKS = 5
COMEBACK_AKTIF = True
COMEBACK_HARI = 14
COMEBACK_XP = 500
COMEBACK_PENGALI = 1.5
COMEBACK_JAM = 24
KABAR_HAMPIR = True
HAMPIR_AMBANG = 100
PET_AKTIF = True
PET_NAMA = 'Nemo'
PET_LAPAR_PER_JAM = 4
PET_KENYANG_PER_CHAT = 0.4
PET_HARGA_MAKAN = 50
PET_ISI_MAKAN = 12
PET_MAKAN_MAKS_HARIAN = 5
PET_SUASANA = [(80, 'riang', '🐠', 1.15), (50, 'biasa aja', '🐟', 1.0), (25, 'lesu', '🥱', 0.95), (0, 'kelaparan', '😵', 0.9)]
CHANNEL_RANTAI = 1536719492334362626
RANTAI_XP = 12
RANTAI_XP_REKOR = 250
RANTAI_HURUF_MIN = 3
KAPSUL_AKTIF = True
KAPSUL_HARI_MIN = 1
KAPSUL_HARI_MAKS = 365
KAPSUL_MAKS_PER_ORANG = 3
KAPSUL_JAM_BUKA = 19
ACARA_INGETIN = 10
ACARA_DM = True
EMOJI_IKUT = '✅'
EMOJI_VOTE = '🌊'
LOMBA_HADIAH = [300, 150, 75]
ROLE_SOAL = ['Island Owner']
WARNA = 4892888